import { NextResponse } from "next/server";


export const GENRE_DATABASE = {
  "Trending Hits": [
  {
    id: "yt_tOM-nWPcR4U",
    youtubeId: "tOM-nWPcR4U",
    title: "Illuminati",
    artist: "Sushin Shyam, Dabzee",
    album: "Aavesham OST",
    duration: 149,
    coverUrl: "https://i.ytimg.com/vi/tOM-nWPcR4U/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "445M"
  },
  {
    id: "yt_60ItHLz5WEA",
    youtubeId: "60ItHLz5WEA",
    title: "Faded",
    artist: "Alan Walker",
    album: "Different World",
    duration: 213,
    coverUrl: "https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "4.0B"
  },
  {
    id: "yt_34Na4j8AVgA",
    youtubeId: "34Na4j8AVgA",
    title: "Starboy",
    artist: "The Weeknd ft. Daft Punk",
    album: "Starboy",
    duration: 230,
    coverUrl: "https://i.ytimg.com/vi/34Na4j8AVgA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "2.8B"
  },
  {
    id: "yt_V9PVRfjEBTI",
    youtubeId: "V9PVRfjEBTI",
    title: "BIRDS OF A FEATHER",
    artist: "Billie Eilish",
    album: "HIT ME HARD AND SOFT",
    duration: 195,
    coverUrl: "https://i.ytimg.com/vi/V9PVRfjEBTI/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.2B"
  },
  {
    id: "yt_r6egHcGiUjs",
    youtubeId: "r6egHcGiUjs",
    title: "Sambar",
    artist: "Dabzee, ThirumaLi, Fejo",
    album: "Sambar Single",
    duration: 204,
    coverUrl: "https://i.ytimg.com/vi/r6egHcGiUjs/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "89M"
  },
  {
    id: "yt_hOHKltAiKXQ",
    youtubeId: "hOHKltAiKXQ",
    title: "Big Dawgs",
    artist: "Hanumankind, Kalmi",
    album: "Big Dawgs Single",
    duration: 234,
    coverUrl: "https://i.ytimg.com/vi/hOHKltAiKXQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "185M"
  },
  {
    id: "yt_eVTXPUF4Oz4",
    youtubeId: "eVTXPUF4Oz4",
    title: "Espresso",
    artist: "Sabrina Carpenter",
    album: "Short n' Sweet",
    duration: 175,
    coverUrl: "https://i.ytimg.com/vi/eVTXPUF4Oz4/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "890M"
  },
  {
    id: "yt_kPa7bsKwL-c",
    youtubeId: "kPa7bsKwL-c",
    title: "Die With A Smile",
    artist: "Lady Gaga, Bruno Mars",
    album: "Die With A Smile",
    duration: 251,
    coverUrl: "https://i.ytimg.com/vi/kPa7bsKwL-c/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "420M"
  },
  {
    id: "yt_H5v3kku4y6Q",
    youtubeId: "H5v3kku4y6Q",
    title: "Not Like Us",
    artist: "Kendrick Lamar",
    album: "Not Like Us",
    duration: 274,
    coverUrl: "https://i.ytimg.com/vi/H5v3kku4y6Q/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "210M"
  },
  {
    id: "yt_ApXoWvfEYVU",
    youtubeId: "ApXoWvfEYVU",
    title: "Sunflower",
    artist: "Post Malone, Swae Lee",
    album: "Spider-Man: Into the Spider-Verse",
    duration: 158,
    coverUrl: "https://i.ytimg.com/vi/ApXoWvfEYVU/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "3.1B"
  },
  {
    id: "yt_TUVcZfQe-Kw",
    youtubeId: "TUVcZfQe-Kw",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: 203,
    coverUrl: "https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "950M"
  },
  {
    id: "yt_ic8j13piAhQ",
    youtubeId: "ic8j13piAhQ",
    title: "Cruel Summer",
    artist: "Taylor Swift",
    album: "Lover",
    duration: 178,
    coverUrl: "https://i.ytimg.com/vi/ic8j13piAhQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.4B"
  }],


  "Malayalam Indie": [
  {
    id: "yt_tOM-nWPcR4U",
    youtubeId: "tOM-nWPcR4U",
    title: "Illuminati",
    artist: "Sushin Shyam, Dabzee",
    album: "Aavesham OST",
    duration: 149,
    coverUrl: "https://i.ytimg.com/vi/tOM-nWPcR4U/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "445M"
  },
  {
    id: "yt_r6egHcGiUjs",
    youtubeId: "r6egHcGiUjs",
    title: "Sambar",
    artist: "Dabzee, ThirumaLi, Fejo",
    album: "Sambar Single",
    duration: 204,
    coverUrl: "https://i.ytimg.com/vi/r6egHcGiUjs/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "89M"
  },
  {
    id: "yt_QUxetheUJVs",
    youtubeId: "QUxetheUJVs",
    title: "Fish Rock",
    artist: "Thaikkudam Bridge",
    album: "Navarasam Live",
    duration: 260,
    coverUrl: "https://i.ytimg.com/vi/QUxetheUJVs/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "48M"
  },
  {
    id: "yt_A0UMazWUS9U",
    youtubeId: "A0UMazWUS9U",
    title: "Chekele",
    artist: "Avial",
    album: "Avial",
    duration: 270,
    coverUrl: "https://i.ytimg.com/vi/A0UMazWUS9U/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "55M"
  },
  {
    id: "yt_HUAAYwtusLI",
    youtubeId: "HUAAYwtusLI",
    title: "Jaada",
    artist: "Sushin Shyam",
    album: "Aavesham",
    duration: 182,
    coverUrl: "https://i.ytimg.com/vi/HUAAYwtusLI/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "62M"
  },
  {
    id: "yt__eWvDaztcjI",
    youtubeId: "_eWvDaztcjI",
    title: "Manavaalan Thug",
    artist: "Dabzee, SA",
    album: "Thallumaala",
    duration: 215,
    coverUrl: "https://i.ytimg.com/vi/_eWvDaztcjI/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "110M"
  },
  {
    id: "yt_ZLtrPJgEHp4",
    youtubeId: "ZLtrPJgEHp4",
    title: "Pala Palli",
    artist: "Jakes Bejoy, Biju Narayanan",
    album: "Kaduva",
    duration: 220,
    coverUrl: "https://i.ytimg.com/vi/ZLtrPJgEHp4/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "98M"
  },
  {
    id: "yt_8ZnWA7hJlwM",
    youtubeId: "8ZnWA7hJlwM",
    title: "Alambanz",
    artist: "Dabzee",
    album: "Alambanz Single",
    duration: 198,
    coverUrl: "https://i.ytimg.com/vi/8ZnWA7hJlwM/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "42M"
  },
  {
    id: "yt_ppQPpShemEE",
    youtubeId: "ppQPpShemEE",
    title: "Karutha Penne",
    artist: "Sanah Moidutty",
    album: "Kerala Classics",
    duration: 240,
    coverUrl: "https://i.ytimg.com/vi/ppQPpShemEE/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "75M"
  },
  {
    id: "yt_W6-O00alJUo",
    youtubeId: "W6-O00alJUo",
    title: "Kuthanthram",
    artist: "Sushin Shyam, Vedan",
    album: "Manjummel Boys",
    duration: 185,
    coverUrl: "https://i.ytimg.com/vi/W6-O00alJUo/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "68M"
  },
  {
    id: "yt_qZ8Qflpn_ZU",
    youtubeId: "qZ8Qflpn_ZU",
    title: "Padayatra",
    artist: "Job Kurian",
    album: "Music Mojo Live",
    duration: 250,
    coverUrl: "https://i.ytimg.com/vi/qZ8Qflpn_ZU/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "24M"
  },
  {
    id: "yt_Tfi3oWgZp1Y",
    youtubeId: "Tfi3oWgZp1Y",
    title: "Lajjavathiye",
    artist: "Jassie Gift",
    album: "4 The People",
    duration: 275,
    coverUrl: "https://i.ytimg.com/vi/Tfi3oWgZp1Y/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "85M"
  }],


  "Global Pop": [
  {
    id: "yt_eVTXPUF4Oz4",
    youtubeId: "eVTXPUF4Oz4",
    title: "Espresso",
    artist: "Sabrina Carpenter",
    album: "Short n' Sweet",
    duration: 175,
    coverUrl: "https://i.ytimg.com/vi/eVTXPUF4Oz4/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "890M"
  },
  {
    id: "yt_V9PVRfjEBTI",
    youtubeId: "V9PVRfjEBTI",
    title: "BIRDS OF A FEATHER",
    artist: "Billie Eilish",
    album: "HIT ME HARD AND SOFT",
    duration: 195,
    coverUrl: "https://i.ytimg.com/vi/V9PVRfjEBTI/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.2B"
  },
  {
    id: "yt_34Na4j8AVgA",
    youtubeId: "34Na4j8AVgA",
    title: "Starboy",
    artist: "The Weeknd ft. Daft Punk",
    album: "Starboy",
    duration: 230,
    coverUrl: "https://i.ytimg.com/vi/34Na4j8AVgA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "2.8B"
  },
  {
    id: "yt_TUVcZfQe-Kw",
    youtubeId: "TUVcZfQe-Kw",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: 203,
    coverUrl: "https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "950M"
  },
  {
    id: "yt_kPa7bsKwL-c",
    youtubeId: "kPa7bsKwL-c",
    title: "Die With A Smile",
    artist: "Lady Gaga, Bruno Mars",
    album: "Die With A Smile",
    duration: 251,
    coverUrl: "https://i.ytimg.com/vi/kPa7bsKwL-c/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "420M"
  },
  {
    id: "yt_ic8j13piAhQ",
    youtubeId: "ic8j13piAhQ",
    title: "Cruel Summer",
    artist: "Taylor Swift",
    album: "Lover",
    duration: 178,
    coverUrl: "https://i.ytimg.com/vi/ic8j13piAhQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.4B"
  },
  {
    id: "yt_GxldQ9eX2wo",
    youtubeId: "GxldQ9eX2wo",
    title: "Until I Found You",
    artist: "Stephen Sanchez",
    album: "Easy On My Eyes",
    duration: 177,
    coverUrl: "https://i.ytimg.com/vi/GxldQ9eX2wo/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "680M"
  },
  {
    id: "yt_tCXGJQYZ9JA",
    youtubeId: "tCXGJQYZ9JA",
    title: "Beautiful Things",
    artist: "Benson Boone",
    album: "Fireworks & Rollerblades",
    duration: 180,
    coverUrl: "https://i.ytimg.com/vi/tCXGJQYZ9JA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "750M"
  },
  {
    id: "yt_4NRXx6U8ABQ",
    youtubeId: "4NRXx6U8ABQ",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: 200,
    coverUrl: "https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "3.5B"
  },
  {
    id: "yt_G7KNmW9a75Y",
    youtubeId: "G7KNmW9a75Y",
    title: "Flowers",
    artist: "Miley Cyrus",
    album: "Endless Summer Vacation",
    duration: 200,
    coverUrl: "https://i.ytimg.com/vi/G7KNmW9a75Y/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "950M"
  },
  {
    id: "yt_suAR1PYFNYA",
    youtubeId: "suAR1PYFNYA",
    title: "Houdini",
    artist: "Dua Lipa",
    album: "Radical Optimism",
    duration: 185,
    coverUrl: "https://i.ytimg.com/vi/suAR1PYFNYA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "310M"
  },
  {
    id: "yt_9gWIIIr2Asw",
    youtubeId: "9gWIIIr2Asw",
    title: "Lose Control",
    artist: "Teddy Swims",
    album: "I've Tried Everything But Therapy",
    duration: 210,
    coverUrl: "https://i.ytimg.com/vi/9gWIIIr2Asw/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "460M"
  }],


  "Hip-Hop & Rap": [
  {
    id: "yt_hOHKltAiKXQ",
    youtubeId: "hOHKltAiKXQ",
    title: "Big Dawgs",
    artist: "Hanumankind, Kalmi",
    album: "Big Dawgs Single",
    duration: 234,
    coverUrl: "https://i.ytimg.com/vi/hOHKltAiKXQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "185M"
  },
  {
    id: "yt_H5v3kku4y6Q",
    youtubeId: "H5v3kku4y6Q",
    title: "Not Like Us",
    artist: "Kendrick Lamar",
    album: "Not Like Us",
    duration: 274,
    coverUrl: "https://i.ytimg.com/vi/H5v3kku4y6Q/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "210M"
  },
  {
    id: "yt_r6egHcGiUjs",
    youtubeId: "r6egHcGiUjs",
    title: "Sambar",
    artist: "Dabzee, ThirumaLi, Fejo",
    album: "Sambar Single",
    duration: 204,
    coverUrl: "https://i.ytimg.com/vi/r6egHcGiUjs/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "89M"
  },
  {
    id: "yt_ApXoWvfEYVU",
    youtubeId: "ApXoWvfEYVU",
    title: "Sunflower",
    artist: "Post Malone, Swae Lee",
    album: "Spider-Man: Into the Spider-Verse",
    duration: 158,
    coverUrl: "https://i.ytimg.com/vi/ApXoWvfEYVU/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "3.1B"
  },
  {
    id: "yt_Dst9gZkq1a8",
    youtubeId: "Dst9gZkq1a8",
    title: "Goosebumps",
    artist: "Travis Scott ft. Kendrick Lamar",
    album: "Birds in the Trap",
    duration: 243,
    coverUrl: "https://i.ytimg.com/vi/Dst9gZkq1a8/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.1B"
  },
  {
    id: "yt_B9synWjqBn8",
    youtubeId: "B9synWjqBn8",
    title: "FE!N",
    artist: "Travis Scott ft. Playboi Carti",
    album: "UTOPIA",
    duration: 191,
    coverUrl: "https://i.ytimg.com/vi/B9synWjqBn8/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "490M"
  },
  {
    id: "yt_22tVWwmTie8",
    youtubeId: "22tVWwmTie8",
    title: "Houdini",
    artist: "Eminem",
    album: "The Death of Slim Shady",
    duration: 227,
    coverUrl: "https://i.ytimg.com/vi/22tVWwmTie8/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "240M"
  },
  {
    id: "yt_Iq8h3GEe22o",
    youtubeId: "Iq8h3GEe22o",
    title: "Lovin On Me",
    artist: "Jack Harlow",
    album: "Lovin On Me",
    duration: 138,
    coverUrl: "https://i.ytimg.com/vi/Iq8h3GEe22o/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "170M"
  },
  {
    id: "yt_V6ZsXKE8QmQ",
    youtubeId: "V6ZsXKE8QmQ",
    title: "fukumean",
    artist: "Gunna",
    album: "A Gift & a Curse",
    duration: 125,
    coverUrl: "https://i.ytimg.com/vi/V6ZsXKE8QmQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "320M"
  },
  {
    id: "yt__VuJA-VQRcY",
    youtubeId: "_VuJA-VQRcY",
    title: "Doja",
    artist: "Central Cee",
    album: "Doja Single",
    duration: 104,
    coverUrl: "https://i.ytimg.com/vi/_VuJA-VQRcY/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "190M"
  },
  {
    id: "yt_tOM-nWPcR4U",
    youtubeId: "tOM-nWPcR4U",
    title: "Illuminati",
    artist: "Sushin Shyam, Dabzee",
    album: "Aavesham OST",
    duration: 149,
    coverUrl: "https://i.ytimg.com/vi/tOM-nWPcR4U/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "445M"
  },
  {
    id: "yt_34Na4j8AVgA",
    youtubeId: "34Na4j8AVgA",
    title: "Starboy",
    artist: "The Weeknd ft. Daft Punk",
    album: "Starboy",
    duration: 230,
    coverUrl: "https://i.ytimg.com/vi/34Na4j8AVgA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "2.8B"
  }],


  "Lo-Fi Study": [
  {
    id: "yt_60ItHLz5WEA",
    youtubeId: "60ItHLz5WEA",
    title: "Faded (Midnight Chill)",
    artist: "Alan Walker",
    album: "Different World",
    duration: 213,
    coverUrl: "https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "4.0B"
  },
  {
    id: "yt_GxldQ9eX2wo",
    youtubeId: "GxldQ9eX2wo",
    title: "Until I Found You",
    artist: "Stephen Sanchez",
    album: "Easy On My Eyes",
    duration: 177,
    coverUrl: "https://i.ytimg.com/vi/GxldQ9eX2wo/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "680M"
  },
  {
    id: "yt_BddP6PYo2gs",
    youtubeId: "BddP6PYo2gs",
    title: "Kesariya",
    artist: "Arijit Singh, Pritam",
    album: "Brahmastra",
    duration: 268,
    coverUrl: "https://i.ytimg.com/vi/BddP6PYo2gs/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "710M"
  },
  {
    id: "yt_mZQH8CPQ-wo",
    youtubeId: "mZQH8CPQ-wo",
    title: "With You (Acoustic)",
    artist: "AP Dhillon",
    album: "With You",
    duration: 154,
    coverUrl: "https://i.ytimg.com/vi/mZQH8CPQ-wo/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "140M"
  },
  {
    id: "yt_cl0a3i2wFcc",
    youtubeId: "cl0a3i2wFcc",
    title: "Lover (Dorm Chill)",
    artist: "Diljit Dosanjh",
    album: "MoonChild Era",
    duration: 184,
    coverUrl: "https://i.ytimg.com/vi/cl0a3i2wFcc/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "195M"
  },
  {
    id: "yt_kdaujIK6eME",
    youtubeId: "kdaujIK6eME",
    title: "Yellow (Acoustic Chill)",
    artist: "Coldplay",
    album: "Parachutes",
    duration: 260,
    coverUrl: "https://i.ytimg.com/vi/kdaujIK6eME/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "520M"
  },
  {
    id: "yt_wGF7PswOENQ",
    youtubeId: "wGF7PswOENQ",
    title: "The Night We Met",
    artist: "Lord Huron",
    album: "Strange Trails",
    duration: 208,
    coverUrl: "https://i.ytimg.com/vi/wGF7PswOENQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "490M"
  },
  {
    id: "yt_MwpMEbgC7DA",
    youtubeId: "MwpMEbgC7DA",
    title: "Another Love",
    artist: "Tom Odell",
    album: "Long Way Down",
    duration: 244,
    coverUrl: "https://i.ytimg.com/vi/MwpMEbgC7DA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "890M"
  },
  {
    id: "yt_2Vv-BfVoq4g",
    youtubeId: "2Vv-BfVoq4g",
    title: "Perfect (Acoustic Study)",
    artist: "Ed Sheeran",
    album: "Divide",
    duration: 263,
    coverUrl: "https://i.ytimg.com/vi/2Vv-BfVoq4g/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.6B"
  },
  {
    id: "yt_V1Pl8CzNzCw",
    youtubeId: "V1Pl8CzNzCw",
    title: "lovely",
    artist: "Billie Eilish ft. Khalid",
    album: "13 Reasons Why",
    duration: 200,
    coverUrl: "https://i.ytimg.com/vi/V1Pl8CzNzCw/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "2.1B"
  },
  {
    id: "yt_OqBuXQLR4Y8",
    youtubeId: "OqBuXQLR4Y8",
    title: "Best Friend",
    artist: "Rex Orange County",
    album: "Best Friend Single",
    duration: 180,
    coverUrl: "https://i.ytimg.com/vi/OqBuXQLR4Y8/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "340M"
  },
  {
    id: "yt_mkqEmQsPzfA",
    youtubeId: "mkqEmQsPzfA",
    title: "Evangeline",
    artist: "Stephen Sanchez",
    album: "Angel Face",
    duration: 178,
    coverUrl: "https://i.ytimg.com/vi/mkqEmQsPzfA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "180M"
  }],


  "College Rock": [
  {
    id: "yt_QUxetheUJVs",
    youtubeId: "QUxetheUJVs",
    title: "Fish Rock",
    artist: "Thaikkudam Bridge",
    album: "Navarasam Live",
    duration: 260,
    coverUrl: "https://i.ytimg.com/vi/QUxetheUJVs/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "48M"
  },
  {
    id: "yt_A0UMazWUS9U",
    youtubeId: "A0UMazWUS9U",
    title: "Chekele",
    artist: "Avial",
    album: "Avial",
    duration: 270,
    coverUrl: "https://i.ytimg.com/vi/A0UMazWUS9U/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "55M"
  },
  {
    id: "yt_YykjpeuMNEk",
    youtubeId: "YykjpeuMNEk",
    title: "Hymn For The Weekend",
    artist: "Coldplay",
    album: "A Head Full of Dreams",
    duration: 258,
    coverUrl: "https://i.ytimg.com/vi/YykjpeuMNEk/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "2.3B"
  },
  {
    id: "yt_aezstCBHOPQ",
    youtubeId: "aezstCBHOPQ",
    title: "Too Sweet",
    artist: "Hozier",
    album: "Unheard",
    duration: 251,
    coverUrl: "https://i.ytimg.com/vi/aezstCBHOPQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "490M"
  },
  {
    id: "yt_7wtfhZwyrcc",
    youtubeId: "7wtfhZwyrcc",
    title: "Believer",
    artist: "Imagine Dragons",
    album: "Evolve",
    duration: 204,
    coverUrl: "https://i.ytimg.com/vi/7wtfhZwyrcc/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "2.7B"
  },
  {
    id: "yt_kXYiU_JCYtU",
    youtubeId: "kXYiU_JCYtU",
    title: "Numb",
    artist: "Linkin Park",
    album: "Meteora",
    duration: 187,
    coverUrl: "https://i.ytimg.com/vi/kXYiU_JCYtU/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "2.3B"
  },
  {
    id: "yt_hTWKbfoikeg",
    youtubeId: "hTWKbfoikeg",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    duration: 278,
    coverUrl: "https://i.ytimg.com/vi/hTWKbfoikeg/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.9B"
  },
  {
    id: "yt_1w7OgIMMRc4",
    youtubeId: "1w7OgIMMRc4",
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    duration: 302,
    coverUrl: "https://i.ytimg.com/vi/1w7OgIMMRc4/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.7B"
  },
  {
    id: "yt_fJ9rUzIMcZQ",
    youtubeId: "fJ9rUzIMcZQ",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    duration: 359,
    coverUrl: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.8B"
  },
  {
    id: "yt_Soa3gO7tL-c",
    youtubeId: "Soa3gO7tL-c",
    title: "Boulevard Of Broken Dreams",
    artist: "Green Day",
    album: "American Idiot",
    duration: 288,
    coverUrl: "https://i.ytimg.com/vi/Soa3gO7tL-c/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "890M"
  },
  {
    id: "yt_pAgnJDJN4VA",
    youtubeId: "pAgnJDJN4VA",
    title: "Back In Black",
    artist: "AC/DC",
    album: "Back in Black",
    duration: 255,
    coverUrl: "https://i.ytimg.com/vi/pAgnJDJN4VA/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.2B"
  },
  {
    id: "yt_V9PVRfjEBTI",
    youtubeId: "V9PVRfjEBTI",
    title: "BIRDS OF A FEATHER (Live)",
    artist: "Billie Eilish",
    album: "HIT ME HARD AND SOFT",
    duration: 195,
    coverUrl: "https://i.ytimg.com/vi/V9PVRfjEBTI/hqdefault.jpg",
    audioUrl: "",
    source: "youtube",
    plays: "1.2B"
  }]

};

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const genre = searchParams.get("name") || "Trending Hits";
  const rawSongs = GENRE_DATABASE[genre] || GENRE_DATABASE["Trending Hits"];
  const songs = rawSongs.slice(0, 12);

  return NextResponse.json({ songs });
}